app_home:
    path: /
    controller: App\Controller\HomeController::index

app_user_signup:
    path: /signup
    controller: App\Controller\UserController::new
app_login:
    path: /login
    controller: App\Controller\AuthController::login
app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
